{% set name = "nicegui" %}
{% set version = "1.4.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zauberzeug/nicegui/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 94e1ac8821ea582929a2941529fe28bacc694d2006d58a6805a1d542d5d6bc63

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.8
    - poetry >=1.3
    - pip
  host:
    - python >=3.8
    - poetry >=1.3
    - pip
  run:
    - python >=3.8
    - typing-extensions >=4.0.0
    - markdown2 >=2.4.7,!=2.4.11
    - pygments >=2.15.1,<3.0.0
    - uvicorn >=0.22.0
    - fastapi >=0.109.1,<0.110.0
    - python-socketio >=5.10.0
    - vbuild >=0.8.2
    - watchfiles >=0.18.1
    - jinja2 >=3.1.3
    - python-multipart >=0.0.7
    - orjson >=3.8.6
    - itsdangerous >=2.1.2
    - aiofiles >=23.1.0
    - httpx >=0.24.0
    - ifaddr >=0.2.0
    - aiohttp >=3.9.2
    - docutils >=0.19
    - libsass = ">=0.22.0"


test:
  imports:
    - nicegui

about:
  home: https://github.com/zauberzeug/nicegui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create web-based interfaces with Python. The nice way.
  doc_url: https://nicegui.io/
  dev_url: https://github.com/zauberzeug/nicegui

extra:
  recipe-maintainers:
    - rodja
    - falkoschindler
