{% set name = "nicegui" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zauberzeug/nicegui/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 78e69e413163c82a97c9bcab7722d8eb7fb8e40ce4e903ad7b1e5580c92de4e9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.8
    - poetry >=1.3
    - pip
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - typing-extensions >=3.10.0
    - markdown2 >=2.4.7,<3.0.0
    - pygments >=2.9.0,<3.0.0
    - uvicorn[standard] >=0.20.0,<0.21.0
    - matplotlib-base >=3.6.0,<4.0.0
    - fastapi >=0.92,<0.93
    - fastapi-socketio >=0.0.10,<0.0.11
    - vbuild >=0.8.1,<0.9.0
    - watchfiles >=0.18.1,<0.19.0
    - jinja2 >=3.1.2,<3.2.0
    - python-multipart >=0.0.6,<0.0.7
    - plotly >=5.13.0,<5.14.0
    - orjson >=3.8.6,<3.9.0
    - importlib_metadata >=6.0.0,<7.0.0

test:
  imports:
    - nicegui
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/zauberzeug/nicegui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create web-based interfaces with Python. The nice way.
  doc_url: https://nicegui.io/
  dev_url: https://github.com/zauberzeug/nicegui

extra:
  recipe-maintainers:
    - rodja
    - falkoschindler
